# Generated by Django 4.1.7 on 2023-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='when_planned',
            field=models.DateField(null=True, verbose_name='Planned to read'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(null=True, verbose_name='blog'),
        ),
    ]
